# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  WebApp-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Eventures.WebApp.SeleniumTests
    - name: Build
      run: dotnet build Eventures.WebApp.SeleniumTests --no-restore
    - name: Test
      run: dotnet test Eventures.WebApp.SeleniumTests --no-build --verbosity normal
    - name: Restore dependencies   
      run: dotnet restore Eventures.WebApp.SeleniumPOMTests 
    - name: Build
      run: dotnet build Eventures.WebApp.SeleniumPOMTests  --no-restore
    - name: Test
      run: dotnet test Eventures.WebApp.SeleniumPOMTests  --no-build --verbosity normal
